const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("mcparser", {
  platform: process.platform,
  stats: (caseDir) => ipcRenderer.invoke("stats", caseDir),
  hosts: (caseDir) => ipcRenderer.invoke("hosts", caseDir),
  collections: (caseDir) => ipcRenderer.invoke("collections", caseDir),
  pickCollection: () => ipcRenderer.invoke("pick-collection"),
  pickCaseSave: () => ipcRenderer.invoke("pick-case-save"),
  makeCaseDir: (parent, name) => ipcRenderer.invoke("make-case-dir", parent, name),
  collect: (caseDir, file) => ipcRenderer.invoke("collect", caseDir, file),
  saveAnalyst: (caseDir, name) => ipcRenderer.invoke("save-analyst", caseDir, name),
  onImportCollection: (handler) => ipcRenderer.on("import-collection", () => handler()),
  query: (caseDir, sql) => ipcRenderer.invoke("query", caseDir, sql),
  saveCsv: (csv) => ipcRenderer.invoke("save-csv", csv),
  queries: (caseDir) => ipcRenderer.invoke("queries", caseDir),
  saveQuery: (caseDir, name, sql) => ipcRenderer.invoke("save-query", caseDir, name, sql),
  notes: (caseDir) => ipcRenderer.invoke("notes", caseDir),
  runs: (caseDir) => ipcRenderer.invoke("runs", caseDir),
  saveRun: (caseDir, rows, sql, label, analyst, kind) => ipcRenderer.invoke("save-run", caseDir, rows, sql, label, analyst, kind),
  saveNote: (caseDir, recordId, body, sql) => ipcRenderer.invoke("save-note", caseDir, recordId, body, sql),
  grokStatus: () => ipcRenderer.invoke("grok-status"),
  setProvider: (name) => ipcRenderer.invoke("set-provider", name),
  grokSave: (key, provider) => ipcRenderer.invoke("grok-save", key, provider),
  grokForget: () => ipcRenderer.invoke("grok-forget"),
  grokAsk: (caseDir, question, provider) => ipcRenderer.invoke("grok-ask", caseDir, question, provider),
  chats: (caseDir) => ipcRenderer.invoke("chats", caseDir),
  saveChat: (caseDir, vendor, question, sql, answer) => ipcRenderer.invoke("save-chat", caseDir, vendor, question, sql, answer),
  exportHandoff: (caseDir, password, out) => ipcRenderer.invoke("export-handoff", caseDir, password, out),
  openHandoff: (file, password, out) => ipcRenderer.invoke("open-handoff", file, password, out),
  pickHandoffSave: () => ipcRenderer.invoke("pick-handoff-save"),
  pickHandoffOpen: () => ipcRenderer.invoke("pick-handoff-open"),
  pickHandoffDir: () => ipcRenderer.invoke("pick-handoff-dir"),
  handoffError: (message) => ipcRenderer.invoke("handoff-error", message),
  onExportHandoff: (handler) => ipcRenderer.on("export-handoff", () => handler()),
  onOpenHandoff: (handler) => ipcRenderer.on("open-handoff", () => handler()),
  onOpened: (handler) => ipcRenderer.on("opened", (_event, payload) => handler(payload)),
  onGrokConnect: (handler) => ipcRenderer.on("grok-connect", (_event, provider) => handler(provider)),
  onGrokChat: (handler) => ipcRenderer.on("grok-chat", (_event, shown) => handler(shown)),
  onGrokStatus: (handler) => ipcRenderer.on("grok-status", (_event, status) => handler(status)),
  onShowNotes: (handler) => ipcRenderer.on("show-notes", () => handler()),
  onShowRuns: (handler) => ipcRenderer.on("show-runs", () => handler()),
  onShowTrail: (handler) => ipcRenderer.on("show-trail", () => handler()),
  onExportTrail: (handler) => ipcRenderer.on("export-trail", () => handler()),
});
