const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("mcparser", {
  platform: process.platform,
  stats: (caseDir) => ipcRenderer.invoke("stats", caseDir),
  hosts: (caseDir) => ipcRenderer.invoke("hosts", caseDir),
  collections: (caseDir) => ipcRenderer.invoke("collections", caseDir),
  prefetch: (caseDir) => ipcRenderer.invoke("prefetch", caseDir),
  pickCollection: () => ipcRenderer.invoke("pick-collection"),
  pickCaseOpen: () => ipcRenderer.invoke("pick-case-open"),
  deleteCase: (caseDir) => ipcRenderer.invoke("delete-case", caseDir),
  onNewCase: (handler) => ipcRenderer.on("new-case", () => handler()),
  onOpenCase: (handler) => ipcRenderer.on("open-case", () => handler()),
  onDeleteCase: (handler) => ipcRenderer.on("delete-case", () => handler()),
  onCloseCase: (handler) => ipcRenderer.on("close-case", () => handler()),
  onSaveCase: (handler) => ipcRenderer.on("save-case", () => handler()),
  setCaseOpen: (open) => ipcRenderer.invoke("set-case-open", open),
  pickCaseSave: () => ipcRenderer.invoke("pick-case-save"),
  makeCaseDir: (parent, name) => ipcRenderer.invoke("make-case-dir", parent, name),
  collect: (caseDir, file, analyst) => ipcRenderer.invoke("collect", caseDir, file, analyst),
  ingest: (caseDir, file) => ipcRenderer.invoke("ingest", caseDir, file),
  chooseCaseTarget: (current) => ipcRenderer.invoke("choose-case-target", current),
  onImportEvtx: (handler) => ipcRenderer.on("import-evtx", (_event, payload) => handler(payload)),
  saveAnalyst: (caseDir, name) => ipcRenderer.invoke("save-analyst", caseDir, name),
  onImportCollection: (handler) => ipcRenderer.on("import-collection", () => handler()),
  onCollectProgress: (handler) => ipcRenderer.on("collect-progress", (_event, payload) => handler(payload)),
  query: (caseDir, sql) => ipcRenderer.invoke("query", caseDir, sql),
  saveCsv: (csv) => ipcRenderer.invoke("save-csv", csv),
  queries: (caseDir) => ipcRenderer.invoke("queries", caseDir),
  saveQuery: (caseDir, name, sql) => ipcRenderer.invoke("save-query", caseDir, name, sql),
  saveSqlFile: (caseDir, suggested, sql) => ipcRenderer.invoke("save-sql-file", caseDir, suggested, sql),
  notes: (caseDir) => ipcRenderer.invoke("notes", caseDir),
  runs: (caseDir) => ipcRenderer.invoke("runs", caseDir),
  huntMatches: (caseDir, runId) => ipcRenderer.invoke("hunt-matches", caseDir, runId),
  marketplace: () => ipcRenderer.invoke("marketplace"),
  installSource: (id, config) => ipcRenderer.invoke("install-source", id, config),
  uninstallSource: (id) => ipcRenderer.invoke("uninstall-source", id),
  importHashes: (id) => ipcRenderer.invoke("import-hashes", id),
  matchHashes: (caseDir) => ipcRenderer.invoke("match-hashes", caseDir),
  onMarketplace: (handler) => ipcRenderer.on("marketplace", () => handler()),
  saveRun: (caseDir, rows, sql, label, analyst, kind) => ipcRenderer.invoke("save-run", caseDir, rows, sql, label, analyst, kind),
  saveNote: (caseDir, recordId, body, sql) => ipcRenderer.invoke("save-note", caseDir, recordId, body, sql),
  grokStatus: () => ipcRenderer.invoke("grok-status"),
  setModel: (provider, model) => ipcRenderer.invoke("set-model", provider, model),
  setProvider: (name) => ipcRenderer.invoke("set-provider", name),
  grokSave: (key, provider) => ipcRenderer.invoke("grok-save", key, provider),
  grokForget: () => ipcRenderer.invoke("grok-forget"),
  grokForgetOne: (provider) => ipcRenderer.invoke("grok-forget-one", provider),
  grokAsk: (caseDir, question, provider) => ipcRenderer.invoke("grok-ask", caseDir, question, provider),
  chats: (caseDir) => ipcRenderer.invoke("chats", caseDir),
  saveChat: (caseDir, vendor, question, sql, answer) => ipcRenderer.invoke("save-chat", caseDir, vendor, question, sql, answer),
  exportHandoff: (caseDir, password, out) => ipcRenderer.invoke("export-handoff", caseDir, password, out),
  openHandoff: (file, password, out) => ipcRenderer.invoke("open-handoff", file, password, out),
  pickHandoffSave: () => ipcRenderer.invoke("pick-handoff-save"),
  pickHandoffOpen: () => ipcRenderer.invoke("pick-handoff-open"),
  pickHandoffDir: () => ipcRenderer.invoke("pick-handoff-dir"),
  handoffError: (message) => ipcRenderer.invoke("handoff-error", message),
  onExportHandoff: (handler) => ipcRenderer.on("export-handoff", () => handler()),
  onOpenHandoff: (handler) => ipcRenderer.on("open-handoff", () => handler()),
  onOpened: (handler) => ipcRenderer.on("opened", (_event, payload) => handler(payload)),
  onGrokConnect: (handler) => ipcRenderer.on("grok-connect", (_event, provider) => handler(provider)),
  onGrokChat: (handler) => ipcRenderer.on("grok-chat", (_event, shown) => handler(shown)),
  onGrokStatus: (handler) => ipcRenderer.on("grok-status", (_event, status) => handler(status)),
  onAskProgress: (handler) => ipcRenderer.on("ask-progress", (_event, label) => handler(label)),
  onShowNotes: (handler) => ipcRenderer.on("show-notes", () => handler()),
  onShowRuns: (handler) => ipcRenderer.on("show-runs", () => handler()),
  onShowTrail: (handler) => ipcRenderer.on("show-trail", () => handler()),
  onExportTrail: (handler) => ipcRenderer.on("export-trail", () => handler()),
  iocs: (caseDir) => ipcRenderer.invoke("iocs", caseDir),
  iocAdd: (caseDir, kind, value, note) => ipcRenderer.invoke("ioc-add", caseDir, kind, value, note),
  iocUpdate: (caseDir, id, kind, value, note) => ipcRenderer.invoke("ioc-update", caseDir, id, kind, value, note),
  iocRemove: (caseDir, id) => ipcRenderer.invoke("ioc-remove", caseDir, id),
  hunt: (caseDir) => ipcRenderer.invoke("hunt", caseDir),
  onHuntProgress: (handler) => ipcRenderer.on("hunt-progress", (_event, payload) => handler(payload)),
  onIocView: (handler) => ipcRenderer.on("ioc-view", () => handler()),
  onIocAdd: (handler) => ipcRenderer.on("ioc-add", () => handler()),
  onIocUpdate: (handler) => ipcRenderer.on("ioc-update", () => handler()),
  onIocRemove: (handler) => ipcRenderer.on("ioc-remove", () => handler()),
});
