[package]
name = "case"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
duckdb = { version = "1.4", features = ["bundled"] }
model = { path = "../model" }
rusqlite = { version = "0.32", features = ["bundled"] }
serde_json = "1"
sha2 = "0.10"
zip = "2"
prefetch-core = "0.1"
notatin = "1"
